@isTest
private class TemperatureConverterTest {
    @isTest static void testWarmTemp(){
        Decimal celsius = TemperatureConverter.FahrenheitToCelsius(70);
        system.assertEquals(21.11,celsius );
    } 
    @isTest static void testFreezingPoint(){
        Decimal celsius = TemperatureConverter.FahrenheitToCelsius(32);
        system.assertEquals(0, celsius);
    }
    @isTest static void testBoilingPoint(){
        Decimal celsius = TemperatureConverter.FahrenheitToCelsius(212);
        system.assertEquals(100, celsius, 'Boiling Point Temperature is not Mandatory');
    }
    @isTest static void testNegativeTemp(){
        Decimal celsius = TemperatureConverter.FahrenheitToCelsius(-10);
        system.assertEquals(-23.33, celsius);
    }

}